### ISSUE TITLE
Feature - Switch to `plotly` to allow graphing in node

### ISSUE THREAD

**Issue by Quantalabs** [epispot/EpiJS#115]
**Is your feature request related to a problem? Please describe.**
The `plots` module is unavailable in NodeJS, and only accessible in the web, which can be a problem to those who need to use NodeJS. This builds a barrier between NodeJS and HTML, and makes the two seem like different libraries. 

**Describe the solution you'd like**
However, using Plotly JavaScript we can extend this capability to NodeJS and keep web support. Plotly also allows for clean and more advanced graphing techniques.

**Describe alternatives you've considered**
Although users on Node could just use Plotly themselves, it prevents users from being able to quickly generate graphs and models.

**Additional context**
This would be a breaking change, and there are other ideas which might also bring breaking changes to the package. So, we'd need to make this a new `v3` version. This would drop support for some `v1` versions, but keeping support for `v2` like we did when with `v1` when `v2` was first released is a good idea. This should also be shipped with #83 and #84, as they both will influence the redesign of the plots module. To put this into effect, we'd like approval from @quantum9Innovation.

**Comment by quantum9Innovation** [comment]
lgtm; /available

**Comment by Quantalabs** [comment]
/claim - I think I need to work on this as I am already working on #84 and #83.

**Comment by Quantalabs** [comment]
Working on this now, before we implement #83

**Comment by Quantalabs** [comment]
We've completed this, but for users on the web, the loading time takes very long, and in some cases, the browser doesn't load the page (like my browser):
![Testing file crashes while running](https://user-images.githubusercontent.com/55121845/148446431-a5bfcb5f-e766-4ef0-b84b-11271dfaed44.png)

**Comment by Quantalabs** [comment]
> We've completed this, but for users on the web, the loading time takes very long, and in some cases, the browser doesn't load the page (like my browser)
It turns out plotly is doing fine, it was just because I was using WSL that it took much longer to load. We should be fine.

**Comment by Quantalabs** [comment]
Next step is to implement this for the `com` module.
