### ISSUE TITLE
Deprecation of the `com` module

### ISSUE THREAD

**Issue by Quantalabs** [epispot/EpiJS#118]
As EpiJS grows more and more advanced, the uses for the `com` module grow smaller and smaller, and it makes it increasingly clear that we might need to deprecate the `com` module moving forward. There is an option of making this a completely separate package which would allow much more complex stats to be implemented. However, I do believe we should deprecate this in the `v3` release.

**Comment by quantum9Innovation** [comment]
A new investigation has uncovered that this module does not actually work. Therefore, I am in full agreement with this proposal. I hereby give my permission to continue this operation.

**Comment by quantum9Innovation** [comment]
Looks good (let's move this to a new package). :package:

**Comment by Quantalabs** [comment]
Completed in 9a55d2fac64f8ef46f8e6f869aac0e8a20d6d253
